### ISSUE TITLE
Getting Internal Errors when using it with the previews

### ISSUE THREAD

**Issue by xDrAcHeNx** [bmachek/lrc-ai-assistant#1] opened 2024-10-16 22:06 UTC
Hi,
i just tried the plugin and i get errors all of the place when trying to tag my cataloge. 
Usually works when reviewing the tags after every picture, but if not i get "internal error " see picture and the script stops working.
![Screenshot 2024-10-17 000614](https://github.com/user-attachments/assets/006493c2-eefa-47e0-8897-8eb9865c9910)

**Comment by bmachek** [comment] 2024-10-17 05:44
Could you please enable logging for the plugin in the module manager, and look at the log file located at Documents/LrClassicLogs/AIPlugin.log after another try?

**Comment by xDrAcHeNx** [comment] 2024-10-17 17:31
yes.
[AIPlugin.log](https://github.com/user-attachments/files/17416657/AIPlugin.log)

**Comment by bmachek** [comment] 2024-10-17 17:40
Ok, looks like Gemini is returning a lot of more less redundant keywords. This only happened very rarely during my development tests.
Can you try using Gemini Pro for a photo just for a test, and see if this makes a difference?

**Comment by xDrAcHeNx** [comment] 2024-10-17 17:48
Pro is getting through the same 10pics just fine

**Comment by bmachek** [comment] 2024-10-17 17:53
Ok. I have to do some testing tomorrow on my side with Gemini flash. Something has changed, it seems...

**Comment by xDrAcHeNx** [comment] 2024-10-17 18:00
i did some testing yesterday, too. When using a picture which usually gets the error only by it self the script gives me actually a blank description and title, before showing the error.

**Comment by bmachek** [comment] 2024-10-18 04:40
So are there some images, on which the error is reproducible?

**Comment by bmachek** [comment] 2024-10-18 04:52
I think the issue is, that the responses with the awful lot keywords aren't valid JSON. Probably the responses are cut off. That leaves the problem how to deal with it, since the error is on Google's side.

**Comment by xDrAcHeNx** [comment] 2024-10-18 13:32
> So are there some images, on which the error is reproducible?
Yes actually a lot pics where flash gives errors and pro don't. And it's reproduceable nearly every single time. After a few tries it may work for a specific pic.




> I think the issue is, that the responses with the awful lot keywords aren't valid JSON. Probably the responses are cut off. That leaves the problem how to deal with it, since the error is on Google's side.

Do you think it would work, if the script just skips the pic with the error and starts the problematic pics of the batch again until they have been tagged correctly, or to introduce an option to retry directly after error? Maybe with the option to switch to pro after a number of tries?

**Comment by xDrAcHeNx** [comment] 2024-10-18 20:44
Another idea, cant we tell gemini that we want the answers in json with an addition to the promt?

**Comment by bmachek** [comment] 2024-10-19 05:05
It would be possible to cancel and redo images that failed.

Answers are already in JSON by prompt, it's just that they are cut off when the answer gets too long. And then the answer isn't valid JSON anymore.

I can implement the redo, but it'll be nothing more than a workaround.

I personally used Gemini Pro for my collection. It's not too  expensive..

**Comment by xDrAcHeNx** [comment] 2024-10-19 08:39
And how about setting a limit of like 25 words for description and tags via
the prompt?

Bastian Machek ***@***.***> schrieb am Sa., 19. Okt. 2024,
07:05:

**Comment by bmachek** [comment] 2024-10-19 11:03
Good idea, will give that a try...

**Comment by bmachek** [comment] 2024-10-20 09:06
I just released 1.1.0 with a possible solution to limit keywords to 25 max via prompt.
Please give it a try.

**Comment by xDrAcHeNx** [comment] 2024-10-20 10:46
Thank you, will try and post log
(On the same ten pics)

**Comment by xDrAcHeNx** [comment] 2024-10-20 13:24
just tried the usual batch of pictures
Flash still gives errors (but not the nil error). May it be because of the german non unicode letters ö,ü,ä,ß?
Pro started to give the 'nil' error
pro 002 had a lot of blank descriptions.
[AIPlugin.log](https://github.com/user-attachments/files/17450385/AIPlugin.log)

**Comment by bmachek** [comment] 2024-10-21 08:14
Yes the problem, that flash generates so many keywords that the response is cut off (by Gemini itself). Then of course the closing brackets are missing. I modified the error handling so that a JSON error doesn't quit the whole operation. I already the instruction to only give 25 keywords max. Then Gemini keeps repeating the same keywords until the response is cut off. I even then added the instruction to generate unique keywords, but this didn't make a difference.

Concerning your second report that caption and title are returned in English, when tags are turned off. This should be an easy fix.

btw, what puzzled me most: https://community.adobe.com/t5/lightroom-classic-discussions/lightroom-classic-sdk-14-0-max-release-now-live/td-p/14915527

The paths of the logfiles changed in LrC 14

**Comment by bmachek** [comment] 2024-10-21 08:35
I asked the Gemini community about this: https://discuss.ai.google.dev/t/bug-report-the-model-often-starts-creating-repetitive-sequences-of-tokens/6445/7?u=bastian_machek

**Comment by xDrAcHeNx** [comment] 2024-10-23 19:08
[AIPlugin.log](https://github.com/user-attachments/files/17497145/AIPlugin.log)

Same Batch of Pictures as always, new error : "internal error: Error decoding json Response."

**Comment by bmachek** [comment] 2024-10-24 04:11
Yes, that's the expected behavior for now. I cannot (yet) stop Gemini flash from sending cut-off responses. But the error should be handled differently and shouldn't stop the batch process.
I'm still looking for a solution for Gemini Flash.

**Comment by xDrAcHeNx** [comment] 2024-10-24 20:04
Well still the batch processing stops with an error

**Comment by bmachek** [comment] 2024-10-25 05:25
Does the whole process stop when there's a photo with an error?
At my installation, it just displays the error and goes on to the next image.

**Closed** 2024-11-04 06:42 UTC
Labels: good first issue
